version: '1.0'
# DevelopMent
services:
  acg2023-book-management:
    build:
      context: .
      dockerfile: Dockerfile
    image: 127.0.0.1:5000/acg2023-book-management
    ports:
      - 6105:6105
    volumes:
      - ./src:/myfolder/src
    env_file:
      - ./.env
    environment:
      - TZ=Asia/Seoul
    restart: always
