name: Code Deploy
on:
  # master 브랜치로 PUSH될 때 마다 이 workflow를 수행
  push:
    branches: ['master']
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          timeout: 60s
          script: |
            cd /ubuntu/slack-book-bot/script.sh
            sh script.sh
